### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by Kepete** [tlorens/ArduinoTurnSignals#1]
Hi, 

Awesome work you have done. The result looks amazing. I'm thinking about making it myself and have some questions.
- Would WS2812 LED strip work the same way as Neopixel? I thought about getting a WS2812 with 144 LEDs per meter, will result in the most accurate and fluid motion. 
- Would it be possible to implement brake lights? Or I'm not in a need for reverse light so probably it would be easy to make it work as a brake light? Just change the color and give input while brake applied.

**Comment by tlorens** [comment]
Anything is possible.  You have plenty of pins to check for voltage with.  The only part that becomes difficult is the logic.  I'm currently battling some problems with the blinkers on/off/on/off detection.  Brake lights are as simple as just checking for voltage on a pin, reacting and setting the lights to red.  You could possibly keep the one half red while brakes are applied and turn-signal is on.   Mock it up on the bench like I did in one of my videos.
